ansible_ssh_user: root
ansible_ssh_pass: root

kube_docker_desired_enabled: yes
kube_docker_desired_state: started

kube_node_type: master

kubernetes_kube_config_logtostderr: "true"
kubernetes_kube_config_verbosity: 0
kubernetes_kube_config_allow_priv: "false"
kubernetes_kube_config_kube_master_endpoint: "http://kube-master:8080"
kubernetes_kube_config_etcd_servers: "http://kube-master:2379"

kubernetes_etcd_config_etcd_name: default
kubernetes_etcd_config_etcd_data_dir: /var/lib/etcd/default.etcd
kubernetes_etcd_config_listen_client_urls: http://0.0.0.0:2379
kubernetes_etcd_config_adv_client_urls: http://0.0.0.0:2379

kubernetes_apiserver_config_api_address: "--address=0.0.0.0"
kubernetes_apiserver_config_api_port: "--port=8080"
kubernetes_apiserver_config_kubelet_port: "--kubelet-port=10250"
kubernetes_apiserver_config_etcd_servers: "--etcd-servers=http://127.0.0.1:2379"
kubernetes_apiserver_config_service_addresses: "--service-cluster-ip-range=10.254.0.0/16"
kubernetes_apiserver_config_api_args: ""
