- name: restart kube-apiserver
  service:
    name: kube-apiserver.service
    state: restarted
  when: kube_node_type == "master"

- name: restart kube-controller-manager
  service:
    name: kube-controller-manager.service
    state: restarted

- name: restart kube-scheduler
  service:
    name: kube-scheduler.service
    state: restarted

- name: restart kubelet
  service:
    name: kubelet.service
    state: restarted

- name: restart kube-proxy
  service:
    name: kube-proxy.service
    state: restarted

- name: restart etcd
  service:
    name: etcd.service
    state: restarted
