### kubelet

- name: configure kubelet
  template:
    src: etc.kubernetes.kubelet.j2
    dest: /etc/kubernetes/kubelet
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kubelet
  when: kube_node_type == "minion"
