### turn off selinux
- selinux:
    state: disabled

### turn off firewall, let docker manage

- name: ensure iptables and firewalld are off, let docker manage it
  service:
    name: "{{ item }}"
    state: stopped
  with_items: ["iptables.service", "firewalld"]
  ignore_errors: yes

### yum repo

- name: install centos 7 virt common repo
  yum_repository:
    name: virt7-docker-common-release
    description: virt7-docker-common-release
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
    gpgcheck: no
    enabled: yes

### kubernetes packages

- name: ensure kubernetes, etcd, and flannel are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: ["kubernetes", "etcd", "flannel"]

### hosts

- name: ensure host files are properly populated
  copy:
    src: "hosts_file"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

### etcd

- block:

  - name: configure etcd server
    template:
      src: etc.etcd.etcd.conf.j2
      dest: /etc/etcd/etcd.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart etcd

  - name: flush etcd
    meta: flush_handlers

  - name: ensure etcd is running
    service:
      name: etcd
      state: started
      enabled: yes

  - name: check if network overlay config is in place
    shell: /usr/bin/etcdctl get /kube-centos/network/config
    register: etcd_check_network_overlay_config
    ignore_errors: yes

  - block:

    - name: deploy etcd network overlay settings init script
      copy:
        src: init_etcd_network_overlay.sh
        dest: /root/init_etcd_network_overlay.sh
        owner: root
        group: root
        mode: 0700

    - name: initialize network overlay settings in etcd
      shell: /bin/sh /root/init_etcd_network_overlay.sh

    when: etcd_check_network_overlay_config.rc != 0

  - name: remove etcd network overlay settings init script
    file:
      path: /root/init_etcd_network_overlay.sh
      state: absent

  when: kube_node_type == "master"

### kubernetes

- name: configure kubernetes config file
  template:
    src: etc.kubernetes.config.j2
    dest: /etc/kubernetes/config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kube-apiserver
    - restart kube-controller-manager
    - restart kube-scheduler
    - restart kubelet
    - restart kube-proxy

- name: configure kubernetes api server
  template:
    src: etc.kubernetes.apiserver.j2
    dest: /etc/kubernetes/apiserver
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kube-apiserver
  when: kube_node_type == "master"
