- block:

  - name: ensure .ssh directory exists
    file:
      path: /root/.ssh
      owner: root
      group: root
      state: directory
      mode: 0700

  - name: ensure default rsa keypair is absent
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.ssh/id_rsa
      - /root/.ssh/id_rsa.pub

  - name: regenerate rsa keypair
    shell: /bin/ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""

  - name: take note of the public key to be added into minions
    set_fact:
      pubkey: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  when: kube_node_type == "master" and kube_regenerate_rsa_key is defined and kube_regenerate_rsa_key

- block:

  - name: ensure .ssh directory exists
    file:
      path: /root/.ssh
      owner: root
      group: root
      state: directory
      mode: 0700

  - name: ensure authorized_keys file exists
    file:
      path: /root/.ssh/authorized_keys
      owner: root
      group: root
      state: file
      mode: 0600

  - name: ensure rsa public key is registered in minion
    lineinfile:
      dest: "/root/.ssh/authorized_keys"
      line: "{{ pubkey }}"
      state: present

  when: kube_node_type == "minion" and kube_regenerate_rsa_key is defined and kube_regenerate_rsa_key
