### service account key

- name: stat service account key
  stat:
    path: "{{ kubernetes_service_account_key_file_path }}"
  register: st_service_account_key
  when: kube_node_type == "master"

- block:

  - name: generate service account key
    shell: "openssl genrsa -out {{ kubernetes_service_account_key_file_path }} 2048"

  - name: set service account key ownership and permission
    file:
      path: "{{ kubernetes_service_account_key_file_path }}"
      owner: kube
      group: kube
      mode: 0700

  - name: restart kube-apiserver and kube-controller-manager
    service:
      name: "{{ item }}"
      state: restarted
    with_items: ["kube-apiserver", "kube-controller-manager"]

  when: kube_node_type == "master" and not st_service_account_key.stat.exists
